version: '3.9'

services:
  scraping_homes:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: scraping_homes_prod
    volumes:
      - .:/app
    env_file:
      - .env
